- docs/installation.md
More precise install docs.
Fixes #
```feature user
```
> Update install docs

- Makefile
- cmd/blueprints/render.go
- go.mod
- go.sum
- vendor/github.com/gardener/landscaper/pkg/apis/config/types_landscaper_config.go
- vendor/github.com/gardener/landscaper/pkg/apis/config/v1alpha1/types_landscaper_config.go
- vendor/github.com/gardener/landscaper/pkg/apis/core/validation/blueprint.go
- vendor/github.com/gardener/landscaper/pkg/landscaper/installations/executions/template/template.go
- vendor/modules.txt
Updates the landscaper dependency and adjusted the render command.
the PR is currently based on my fork and will be updated as soon as https://github.com/gardener/landscaper/pull/79 is merged.
```feature user
NONE
```
> update landscaper and adjust render changes

- docs/reference/landscaper-cli_components-cli_component-archive_remote_get.md
- docs/reference/landscaper-cli_components_add_helm-ls_deployitem.md
- go.mod
- go.sum
- vendor/github.com/gardener/component-cli/ociclient/credentials/builder.go
- vendor/github.com/gardener/component-cli/ociclient/credentials/keyring.go
- vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/remote/get.go
- vendor/modules.txt
Fixes #
```other dependency
Update component-cli to v0.8.0 which includes a bugfix to use the default os native credential store
```
> update component-cli to v0.8.0

- cmd/components/add_helm_ls_deployitem.go
- cmd/components/add_manifest_deployitem.go
- cmd/components/add_manifest_deployitem_test.go
- docs/commands/create_component/create.md
- docs/commands/create_component/resources/02-step-add-helm-chart-in-oci/demo-component/blueprint/blueprint.yaml
- docs/commands/create_component/resources/02-step-add-helm-chart-in-oci/demo-component/blueprint/deploy-execution-nginx.yaml
- docs/commands/create_component/resources/03-step-add-local-helm-chart/demo-component/blueprint/blueprint.yaml
- docs/commands/create_component/resources/03-step-add-local-helm-chart/demo-component/blueprint/deploy-execution-echo.yaml
- docs/commands/create_component/resources/03-step-add-local-helm-chart/demo-component/blueprint/deploy-execution-nginx.yaml
- docs/commands/create_component/resources/03-step-add-local-helm-chart/demo-component/resources.yaml
- docs/commands/create_component/resources/04-step-add-secret-manifests/demo-component/blueprint/blueprint.yaml
- docs/commands/create_component/resources/04-step-add-secret-manifests/demo-component/blueprint/deploy-execution-echo.yaml
- docs/commands/create_component/resources/04-step-add-secret-manifests/demo-component/blueprint/deploy-execution-nginx.yaml
- docs/commands/create_component/resources/04-step-add-secret-manifests/demo-component/blueprint/deploy-execution-secrets.yaml
- docs/commands/create_component/resources/04-step-add-secret-manifests/demo-component/resources.yaml
- docs/commands/create_component/resources/05-step-prepare-push/demo-component/blueprint/blueprint.yaml
- docs/commands/create_component/resources/05-step-prepare-push/demo-component/blueprint/deploy-execution-echo.yaml
- docs/commands/create_component/resources/05-step-prepare-push/demo-component/blueprint/deploy-execution-nginx.yaml
- docs/commands/create_component/resources/05-step-prepare-push/demo-component/blueprint/deploy-execution-secrets.yaml
- docs/commands/create_component/resources/05-step-prepare-push/demo-component/component-descriptor.yaml
- docs/commands/create_component/resources/05-step-prepare-push/demo-component/resources.yaml
- docs/commands/create_component/resources/manifests/set1/demo-secret-1.yaml
- docs/commands/create_component/resources/manifests/set1/demo-secret-2.yaml
- docs/reference/landscaper-cli.md
- docs/reference/landscaper-cli_installations.md
- docs/reference/landscaper-cli_installations_create.md
- pkg/blueprints/templates.go
Fixes #
```feature user
- Allow "-" in import parameter names
```
> Param names with minus

- integration-test/main.go
- integration-test/tests/test_component_create.go
This PR adds an integration test for the creation of a component with blueprint.
> Integration test for create component

- cmd/components/add.go
- cmd/components/add_container.go
- cmd/components/add_container_deployitem.go
- cmd/components/add_container_deployitem_test.go
- cmd/components/add_helm_ls_deployitem.go
- cmd/components/add_manifest_deployitem.go
- docs/commands/container_deployer/add_container_di.md
- docs/commands/container_deployer/resources/01-create-component/demo-component/blueprint/blueprint.yaml
- docs/commands/container_deployer/resources/01-create-component/demo-component/component-descriptor.yaml
- docs/commands/container_deployer/resources/01-create-component/demo-component/resources.yaml
- docs/commands/container_deployer/resources/02-add-container-deploy-item/demo-component/blueprint/blueprint.yaml
- docs/commands/container_deployer/resources/02-add-container-deploy-item/demo-component/blueprint/deploy-execution-examplecontainer.yaml
- docs/commands/container_deployer/resources/02-add-container-deploy-item/demo-component/component-descriptor.yaml
- docs/commands/container_deployer/resources/02-add-container-deploy-item/demo-component/resources.yaml
- docs/commands/container_deployer/resources/image-resources/Dockerfile
- docs/commands/container_deployer/resources/image-resources/script.sh
- docs/commands/container_deployer/resources/installations/installation.yaml
- docs/internal/drafts/container-deployer/demo-component/Dockerfile
- docs/internal/drafts/container-deployer/demo-component/blueprint/deploy-execution-container1.yaml
- docs/internal/drafts/container-deployer/demo-component/component-descriptor.yaml
- docs/internal/drafts/container-deployer/demo-component/installation.yaml
- docs/internal/drafts/container-deployer/demo-component/readme.md
- docs/internal/drafts/container-deployer/demo-component/script.sh
- docs/reference/landscaper-cli_components_add.md
- docs/reference/landscaper-cli_components_add_container.md
- docs/reference/landscaper-cli_components_add_container_deployitem.md
- docs/reference/landscaper-cli_components_add_helm-ls_deployitem.md
- docs/reference/landscaper-cli_components_add_manifest_deployitem.md
- pkg/blueprints/blueprint_builder.go
This PR introduces a new command to add a deploy item for the container controller 
```feature user
- New command: landscaper-cli components add container deployitem
```
> Command to add a deploy item for the container controller

- cmd/quickstart/add_oci_endpoint.go
- cmd/quickstart/oci_registry.go
- docs/commands/quickstart/install.md
Check the length of oci endpoint
Fixes #
```feature user
- check the length of OCI registry endpoint and changes url prefix from oci. to o.
```
> Check endpoint length

- cmd/blueprints/render.go
- cmd/blueprints/render_test.go
- cmd/blueprints/testdata/00-render/blueprint/blueprint.yaml
- cmd/blueprints/testdata/00-render/component-descriptor.yaml
- cmd/blueprints/testdata/00-render/imports.yaml
- vendor/github.com/mandelsoft/vfs/pkg/layerfs/doc.go
- vendor/github.com/mandelsoft/vfs/pkg/layerfs/file.go
- vendor/github.com/mandelsoft/vfs/pkg/layerfs/filedata.go
- vendor/github.com/mandelsoft/vfs/pkg/layerfs/layer.go
- vendor/modules.txt
Fixes https://github.com/gardener/landscapercli/issues/46
Please also have a look at the unit tests if it complies to your other tests.
```feature user
Additional import values have been added to the render command.
```
> Add additional import values for local templating

- cmd/app.go
- cmd/completion/completion.go
- docs/installation.md
- docs/reference/landscaper-cli.md
- docs/reference/landscaper-cli_completion.md
Adds an autocompletion command and a documentation on how to use it with different shells.
Fixes #52 
```feature user
Added: Autocompletion with command description
```
> Enable autocompletion

- docs/reference/landscaper-cli_quickstart_install.md
- go.mod
- go.sum
- pkg/blueprints/blueprint_writer.go
- pkg/util/util.go
- pkg/version/version_info.go
- vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
- vendor/modules.txt
Upgrade to landscaper v0.11.2
Fixes #
```feature user
- Upgrade to landscaper v0.11.2
```
> Upgrade to landscaper v0.11.2

- cmd/quickstart/install.go
- docs/reference/landscaper-cli_quickstart.md
- docs/reference/landscaper-cli_quickstart_install.md
enable default deployers in quickstart install
Fixes #97 
```feature user
enable default deployers in quickstart install
```
> enable default deployers in quickstart install

- cmd/quickstart/install.go
- cmd/quickstart/install_test.go
- cmd/quickstart/oci_registry.go
- cmd/quickstart/uninstall.go
- docs/reference/landscaper-cli_quickstart_uninstall.md
- integration-test/main.go
- pkg/util/util.go
- use shorter error handling syntax
- unify logs, error messages, parameter descriptions, ...
Fixes #
```feature user
```
> refactoring

- cmd/quickstart/install.go
bugfix: always use default deployer configuration, not only when installing the oci registry
Fixes #
```feature user
```
> always use default deployer configuration

- cmd/quickstart/uninstall.go
- docs/reference/landscaper-cli_quickstart_uninstall.md
Uninstall complete landscaper including deployer registrations and namespace
Fixes #
```feature user
Uninstall complete landscaper including deployer registrations and namespace.
```
> Uninstall landscaper correctly

- pkg/util/util.go
Remove force delete in integration tests
Fixes #
```feature user
NONE
```
> Remove force delete in integration tests

- hack/install-cli.sh
fix gitTreeState. 
Previous script was always returning "dirty".
Signed-off-by: vasu1124 <vasu1124@actvirtual.com>
> fix gitTreeState; was always returning dirty

- cmd/installations/force_delete.go
- cmd/installations/inspect.go
- cmd/installations/installations.go
- docs/reference/landscaper-cli_installations.md
- docs/reference/landscaper-cli_installations_force-delete.md
- pkg/util/k8sclient.go
This PR add a command to force-delete an installation with all dependent objects. No guarantee is given with respect to the installed software.
Fixes #
```feature user
```
> Force delete

- cmd/installations/force_delete.go
Previously, the force-reconcile command had deleted objects "top-down" (installation -> execution -> deploy item).
With this pull request, the objects are deleted in the reverse order (deploy item -> execution -> installation).
The advantage is that in case of an error an upper section of the object tree remains, so that the command can be repeated.
More precisely, the deletions which add the deletion timestamp are still done downwards, beginning with the root installation. But the finalizers are then removed upwards. 
Fixes #
```feature user
- force-delete command
```
> Improve force-delete command

- docs/commands/quickstart/install.md
Adapt the quickstart doc to the current behaviour.
Fixes #
```feature user
NONE
```
> Adapt quickstart docu

- .ci/pipeline_definitions
**What this PR does / why we need it**:#
alpine 3.13 end of support 2022-11-01
for 3.15 it's 2023-11-01 
Fixes #
```feature user
```
> Update to alpine:3.15

- docs/commands/container_deployer/add_container_di.md
- docs/commands/container_deployer/resources/installations/installation.yaml
- docs/commands/create_component/resources/installations/installation-for-normal-oci-registry.yaml
- docs/commands/create_component/resources/installations/installation-for-quickstart-oci-registry.yaml
- docs/commands/installations/create.md
- docs/examples/component-descriptor-blueprint/installation.yaml
- docs/examples/inline-blueprint/installation.yaml
Improve documentation with respect to new reconcile logic.
Fixes #
```feature user
NONE
```
> Improve documentation with respect to new reconcile logic

- cmd/quickstart/install.go
- cmd/quickstart/install_test.go
Before this change, the `landscaper-cli quickstart install` command did not respect the list of deployers specified in the landscaper values file but always overrode it with a hardcoded list containing `container`, `helm`, and `manifest`.
Now it will only add this default list if no deployer list is given in the landscaper values file, otherwise it will not overwrite the configured deployer list.
```feature user
The `landscaper-cli quickstart install` command will now respect the list of deployers given in the landscaper values file instead of always overwriting it. It will still add the default list if the landscaper values file does not contain a list of deployers.
```
> don't overwrite given deployers

- docs/reference/landscaper-cli_component-cli_component-archive_remote_copy.md
- docs/reference/landscaper-cli_component-cli_component-archive_signatures_sign.md
- docs/reference/landscaper-cli_component-cli_component-archive_signatures_sign_rsa.md
- docs/reference/landscaper-cli_component-cli_component-archive_signatures_sign_signing-server.md
- go.mod
- go.sum
- vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/remote/copy.go
- vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/sign/rsa.go
- vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/sign/sign.go
- vendor/github.com/gardener/component-cli/pkg/commands/componentarchive/signature/sign/signing_server.go
- vendor/modules.txt
```other developer
Upgrade component-cli to `v0.47.0`
```
> upgrade component-cli dependency to v0.47.0

- cmd/blueprints/render.go
The component references were not resolved recursively. This would lead to a templating error in the blueprints render command if a nested component reference would be accessed. 
```feature user
Resolve remote component descriptor references recursively during bluerints render command.
```
> resolve component reference recursively

- cmd/installations/inspect/collector.go
Build object tree for inspect command.
Fixes #
```feature user
- Fix inspect command
```
> Build object tree for inspect command

- docs/commands/quickstart/install.md
Just a small PR that fixes a typo.
Fixes #
```feature user
```
> doc: Typo in documentation

- .ci/ensure-go
- .ci/pipeline_definitions
Fixes #
```other dependency
NONE
```
> Integration tests on go 1.21.7 and alpine 3.19

- README.md
Fix a small glitch in the installation instruction
There is a glitch in the installation instruction.
Fixes the glitch.
NONE
> Fix installation docu in README.md

- .ci/ensure-go
- .ci/pipeline_definitions
- go.mod
Fixes #
```other dependency
Update to go 1.23.6
```
> chore(deps): Update to go 1.23.6
