cmd/installations/installations.go
cmd/installations/set_input_parameters.go
cmd/installations/set_input_parameters_test.go

Added: installation set-input-parameters
```feature user
installation set-input-parameters command to set static values for imports
```

Added: installation set-input-parameters

---

cmd/installations/create.go
cmd/installations/set_import_parameters.go
cmd/installations/set_import_parameters_test.go
docs/reference/landscaper-cli_installations_create.md
docs/reference/landscaper-cli_installations_set-import-parameters.md

Added: create installation and set-import parameters file output
set-import-parameters now tells the user if a given import parameter is not found in a blueprint
Fixes #
```feature user
```

Added: create installation and set-import parameters file output

---

cmd/blueprints/render.go
cmd/blueprints/render_test.go
cmd/blueprints/testdata/00-render/imports.yaml
cmd/blueprints/types.go
docs/reference/landscaper-cli_blueprints_render.md

Fixes #47
```feature user
The imports that are specified for the render command are now validated.
This also enables developers to test jsonschema definitions.
```

add import validation in the render command

---

pkg/util/util.go
pkg/util/util_test.go

allow both old and new blueprint resource types in util method (referenced in "installations create")
Fixes #
```bugfix user
- "installations create" now works for both the old and new blueprint resource types (referenced in the component descriptor)
```

allow old and new blueprint resource types in util method

---

cmd/targets/types/kubernetes_cluster.go
docs/reference/landscaper-cli_targets_create_kubernetes-cluster.md

improvements for "targets create" cmd
- better error messages
- makes namespace flag optional
Fixes #
```feature user
-  --namespace flag in "targets create" cmd is now optional
```

updates targets create cmd

---

cmd/installations/create.go
cmd/installations/create_test.go
integration-test/main.go
integration-test/tests/test_installations_create.go
pkg/util/cmd.go

use the last repository context in the "installations create" cmd
Fixes #
```bugfix user
- use the last repository context in the "installations create" cmd
```

always use last repo context in installations create cmd

---

integration-test/tests/test_installations_create.go

This PR fixes the integration test of the landscaper cli. Currently, the test fails, because the repository context of an installation is not as expected.  However, the difference is just the field order in the raw yaml representation. The parsed objects are equal. The fix excludes the raw yaml from the check and only compares the objects.
Fixes #
```feature user
NONE
```

Fix integration test

---

cmd/blueprints/render.go
cmd/blueprints/render_test.go
docs/commands/create_component/create.md
docs/examples/component-descriptor-blueprint/README.md
integration-test/tests/test_installations_create.go

This PR allows calling the render command with arguments containing relative paths.
Fixes #
```bugfix user
- render command could be called with relative paths
```

Render with relative paths

---

cmd/quickstart/install.go

This pull request fixes issue #104 of the `quickstart install` command. The namespace specified in the command is now also used as namespace for the deployers and the installations which create them.
Fixes #104 
```bugfix user
- Command "quickstart install" can be used with another namespace than "ls-system".
```

Set namespace for installations and deployers

---

integration-test/main.go

Removes the namespace of landscaper installation in integration tests
Fixes #
```feature user
NONE
```

Remove ns of landscaper installation in integration tests

---

cmd/components/add_helm_ls_deployitem.go
cmd/components/create.go
pkg/components/resource_writer.go

This PR fixes issue #113 .
Fixes #113 
```bugfix user
- Fixes an issue with command `landscaper-cli component add helm-ls deployitem` if the provided chart-directory ends with a slash.
```

Fix issue with parent directory calculation

---

docs/commands/blueprints/render.md
docs/examples/render-blueprint/01-render-with-values/blueprint/blueprint.yaml
docs/examples/render-blueprint/01-render-with-values/render.sh
docs/examples/render-blueprint/01-render-with-values/values.yaml

This PR extends the documentation of the render blueprint command.
It adds links to the examples in the [landscaper-examples](https://github.com/gardener/landscaper-examples/tree/master/render-blueprint) repository. 
Fixes #
```doc user
- Documentation of the render blueprint command
```

Render blueprint documentation

---

Makefile
hack/cross-build.sh
hack/install-cli.sh

Automatic determination of correct landscaper version during build. 
Fixes #
```feature user
Automatic determination of correct landscaper version during build.
```

automatic landscaper version determination

---

integration-test/main.go
integration-test/tests/test_component_create.go

During some runs of the integration test, there are some resources with finalizers left in the test namespaces.
These resources prevent the namespaces to be deleted.
This PR introduces a change that attempts to clean-up all remaining landscaper resources in the test namespaces before running the test cases.
```feature user
NONE
```

integration test cleanup

---

docs/commands/create_component/create.md
docs/commands/create_component/resources/02-step-add-helm-chart-in-oci/demo-component/resources.yaml
docs/commands/create_component/resources/03-step-add-local-helm-chart/demo-component/resources.yaml
docs/commands/create_component/resources/04-step-add-secret-manifests/demo-component/resources.yaml
docs/commands/create_component/resources/05-step-prepare-push/demo-component/component-descriptor.yaml
docs/commands/create_component/resources/05-step-prepare-push/demo-component/resources.yaml

Improve documentation by updating the ingress-nginx version of the create_component tutorial. With the previous version, the following error occurred when trying to deploy the nginx controller:
`Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource`
Fixes #
```doc developer
NONE
```

Update ingress-nginx version v0.1.0 -> 4.0.18

---

.ci/pipeline_definitions
cmd/blueprints/push.go
cmd/blueprints/validate.go
cmd/components/add_manifest_deployitem.go
cmd/installations/inspect/collector.go
cmd/installations/inspect/printer.go
cmd/installations/inspect/transformer.go
cmd/installations/inspect/tree.go
cmd/installations/set_import_parameters.go
cmd/quickstart/install.go
integration-test/main.go
integration-test/tests/test_component_create.go
integration-test/tests/test_installations_create.go
pkg/blueprints/blueprint_builder.go
pkg/blueprints/blueprint_reader.go
pkg/components/component_descriptor_reader.go
pkg/util/k8sclient.go
pkg/util/util.go

I'd like to upgrade golang, but since the tests run in the pipeline are based on the pipeline definitions in the `master` branch, the PR won't get green if we don't upgrade the images used by the pipeline first.
```feature user
NONE
```

Upgrade golang images

---

cmd/targets/create.go
cmd/targets/types/generic.go
cmd/targets/types/kubernetes_cluster.go
docs/reference/landscaper-cli_targets_create.md
docs/reference/landscaper-cli_targets_create_kubernetes-cluster.md
integration-test/main.go
integration-test/tests/test_installations_create.go
pkg/util/util.go

It is now possible to have the `landscaper-cli targets create` subcommand put the content in a secret (which is referenced in the target) instead of in the target directly.
```feature user
The `landscaper-cli targets create` subcommand now offers a `--secret` flag. When given together with a secret name, the command will create two manifests instead of one: one for a secret with the given name which contains the actual content, and one with a target which references this secret.
```
```other developer
The coding around the `targets create` subcommand has been refactored. The logic handling targets with secret references as well as the logic responsible for writing the output to a file instead of stdout have been extracted from the …
```

Enable 'target create' subcommand to store content in secret

---

cmd/quickstart/install.go
cmd/quickstart/install_test.go

Fixes a bug in rendering the landscaper values overwrite when no deployers are specified.
/area ipcei
/area usability
/kind regression
```bugfix user
Fixed a bug in the `landscaper-cli quickstart install` subcommand which caused the default deployers (when no deployers are specified) to be inserted at the wrong position in the values overwrite file. This had the effect that the Landscaper would be deployed without any deployers, instead of using the default set as intended.
```

fix default deployers

---

.reuse/dep5
README.md
flake.lock
flake.nix

We want to enable landscapercli for the nix community.
```feature user
nix run github:gardener/landscapercli -- version
nix profile install github:gardener/landscapercli
landscaper-cli --help
```

Nix flake enablement for landscapercli

---

.ci/dev_integration_test
cmd/quickstart/helper.go
cmd/quickstart/install.go
cmd/quickstart/install_test.go
cmd/quickstart/quickstart.go
cmd/quickstart/uninstall.go
cmd/version/version.go
docs/commands/quickstart/install.md
docs/commands/quickstart/uninstall.md
docs/reference/landscaper-cli_quickstart_install.md
docs/reference/landscaper-cli_quickstart_uninstall.md
flake.nix
hack/cross-build.sh
hack/install-cli.sh
integration-test/main.go
integration-test/tests/test_component_create.go
integration-test/tests/test_quickstart_install.go
integration-test/util/config.go
integration-test/util/lscontext.go
integration-test/util/util.go
pkg/util/util.go
pkg/version/release.go
pkg/version/version_info.go

Modify the quickstart install/uninstall commands such that the Landscaper agent logic including the deployer registration is not used anymore. 
Fixes #
```other user
- remove dependency to Landscaper agent logic
- install latest Landscaper release as default
- flag remove-crds to remove all CRDs and CRs of landscaper types
- no configuration yaml required for installation 
```

Remove agent logic

---

cmd/installations/inspect/transformer.go

This PR fixes the following bug:
The command `landscaper-cli installation inspect` fails with a nilpointer in the following situation:
- the installation has no component descriptor &mdash; this is typically the case if it has an inline blueprint,
- and if the command is called with the option `-o wide` (or `--owide` or `-w`).
Fixes #
```bugfix user
- Fix for a nilpointer in the inspect command when executed with option "-o wide"
```

Fix nilpointer in inspect command

---

hack/cross-build.sh

Build executable for windows amd64 architecture.
Fixes #
```feature user
- Executable for windows amd64 architecture
```

Build executable for windows amd64 architecture
